### ISSUE TITLE
Shadowland's Lua Error

### ISSUE THREAD

**Issue by raineday** [Wutname1/FunFact#1]
7x FunFact\libs\StdUi\StdUi-5.lua:119: attempt to call method 'SetBackdrop' (a nil value)
[string "@FunFact\libs\StdUi\StdUi-5.lua"]:119: in function `ApplyBackdrop'
[string "@FunFact\libs\StdUi\widgets\Basic.lua"]:20: in function `Panel'
[string "@FunFact\libs\StdUi\widgets\Basic.lua"]:36: in function `PanelWithTitle'
[string "@FunFact\libs\StdUi\widgets\Window.lua"]:13: in function `Window'
[string "@FunFact\FunFact-1.2.lua"]:149: in function <FunFact\FunFact.lua:124>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by raineday** [comment]
Seems to have fixed itself maybe with an ace3 update.

**Comment by Wutname1** [comment]
> Seems to have fixed itself maybe with an ace3 update.

Nope Finally, Released a shadowlands update the other day.
